/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiographyRouteImport } from './routes/biography'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as PublicationsRouteImport } from './routes/publications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiographyRoute = BiographyRouteImport.update({
  id: '/biography',
  path: '/biography',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/publications': typeof PublicationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/publications': typeof PublicationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biography': typeof BiographyRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/publications': typeof PublicationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/biography' | '/contact' | '/exhibitions' | '/publications'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/biography' | '/contact' | '/exhibitions' | '/publications'
  id:
    | '__root__'
    | '/'
    | '/biography'
    | '/contact'
    | '/exhibitions'
    | '/publications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiographyRoute: typeof BiographyRoute
  ContactRoute: typeof ContactRoute
  ExhibitionsRoute: typeof ExhibitionsRoute
  PublicationsRoute: typeof PublicationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biography': {
      id: '/biography'
      path: '/biography'
      fullPath: '/biography'
      preLoaderRoute: typeof BiographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiographyRoute: BiographyRoute,
  ContactRoute: ContactRoute,
  ExhibitionsRoute: ExhibitionsRoute,
  PublicationsRoute: PublicationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
